### ISSUE TITLE
Remaining tasks

### ISSUE THREAD

**Issue by mghosh00** [SABS-R3-Epidemiology/abm-project-2023#20]
Here are a list of remaining tasks for this project. Please add any if new ones come up or tick them if tasks have been completed. Also, create the task into an issue if you are completing the task, and assign yourself/others to this new issue.

### Documentation (note - please add all changes to the feature-documentation branch) #7 :

- [x] Update README.md to include a list of parameters, a description of how the model works and a biological interpretation of the model
- [x] Create a Wiki for the project #22 
- [x] Need docstrings under all functions
- [x] Once finished, edit the UML class diagram to have it fully up to date with our class structure, and add the final version to README.md
- [x] Have .readthedocs.yml fully setup and working
- [x] Go to #5 and make sure that all variables are accounted for at the end of the project

### Code enhancement:

- [x] Ensure that there is a command to generate gif_plot.py as a separate feature for the user

### Testing:

- [x] Achieve 100% code coverage for the initial model (minicell.py, plot.py, person.py, status.py)
- [x] #23
- [x] Write tests for the tree diagram branch and achieve 100% code coverage (gif_plot.py)

### Setup:

- [x] Ensure that all setup files (setup.py, pyproject.toml, __init__.py) are fully up to date with all modules referenced as in #18
